### ISSUE TITLE
Problem with installing/running libspotify-node

### ISSUE THREAD

**Issue by MPV** [liesen/libspotify-node#1]
Hi guys, 
This looks like an awesome idea! Nice work! I'd love to be able to make a Spotify-client in Node.js. My idea right now is to build a client that adds the feature of multiple users being able to vote up/down songs in a playlist to indirectly change the order of the songs in the playlist. Perfect for events where the participants can add/vote for songs but the play order cannot be interrupted unless enough votes determine that it should. 

So...
I tried to download, install and run this code but I couldn't get it to work. Is it in a working state? 

I began with installing Nodejs v0.1.102 and libspotify v0.0.4. 

Then I cloned your git repo and ran "node-waf configure build test" but got this error:

```
$ node-waf configure build test
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/vs/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.057s)
Waf: Entering directory `/Users/vs/Sites/libspotify-node/build'
[ 1/11] cxx: src/search.cc -> build/default/src/search_1.o
[ 2/11] cxx: src/album.cc -> build/default/src/album_1.o
[ 3/11] cxx: src/artist.cc -> build/default/src/artist_1.o
[ 4/11] cxx: src/user.cc -> build/default/src/user_1.o
[ 5/11] cxx: src/track.cc -> build/default/src/track_1.o
[ 6/11] cxx: src/index.cc -> build/default/src/index_1.o
[ 7/11] cxx: src/playlistcontainer.cc -> build/default/src/playlistcontainer_1.o
[ 8/11] cxx: src/session.cc -> build/default/src/session_1.o
[ 9/11] cxx: src/playlist.cc -> build/default/src/playlist_1.o
[10/11] cxx: src/callback_queue.cc -> build/default/src/callback_queue_1.o
[11/11] cxx_link: build/default/src/search_1.o build/default/src/album_1.o build/default/src/artist_1.o build/default/src/user_1.o build/default/src/track_1.o build/default/src/index_1.o build/default/src/playlistcontainer_1.o build/default/src/session_1.o build/default/src/playlist_1.o build/default/src/callback_queue_1.o -> build/default/binding.node
Waf: Leaving directory `/Users/vs/Sites/libspotify-node/build'
'build' finished successfully (4.952s)
>>> running 7 tests
>>> run test-login.js


module:243
      throw new Error("Cannot find module '" + request + "'");
            ^
Error: Cannot find module '../account'
    at loadModule (module:243:13)
    at require (module:374:12)
    at Object.<anonymous> (/Users/vs/Sites/libspotify-node/test/test.js:4:15)
    at Module._compile (module:423:23)
    at Module._loadScriptSync (module:433:8)
    at Module.loadSync (module:306:10)
    at loadModule (module:251:12)
    at require (module:374:12)
    at Object.<anonymous> (/Users/vs/Sites/libspotify-node/test/test-login.js:1:63)
    at Module._compile (module:423:23)
>>> fail test-login.js -- status 11
>>> ran 1 of 7 tests with 1 failure(s)
tests failed
```

So I cloned account.js.in to account.js and added my username, password and application key. Then I ran "node-waf configure build test" again and this is where I am stuck with this error:

```
$ node-waf configure build test
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/vs/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.036s)
Waf: Entering directory `/Users/vs/Sites/libspotify-node/build'
Waf: Leaving directory `/Users/vs/Sites/libspotify-node/build'
'build' finished successfully (0.968s)
>>> running 7 tests
>>> run test-login.js
>>> fail test-login.js -- status null
>>> ran 1 of 7 tests with 1 failure(s)
tests failed
```

Does this mean that it's not working at all? Or just that the test isn't working? 

If I run "sudo node-waf install" it seems to work alright: 

```
$ sudo node-waf install
Waf: Entering directory `/Users/vs/Sites/libspotify-node/build'
* installing build/default/binding.node as /Users/vs/.node_libraries/binding.node
Waf: Leaving directory `/Users/vs/Sites/libspotify-node/build'
'install' finished successfully (1.178s)
```

If I then try to run any of the examples like this, I get a segmentation fault:

```
$ node examples/logging_in.js 
Segmentation fault
```

Maybe I just missed something easy? Maybe I'm trying this out before you have even remotely had a chance to finish it? 

Thanks for your time.

**Comment by liesen** [comment]
Development has been rather slow lately. I also got the segfault you describe and traced it to the atomic queue which I had no idea how to debug so I've ripped that out and replaced it with the queue implementation from STL _which is not thread safe!_ for now. Update the source and try again. Thanks for reporting problem!

**Comment by MPV** [comment]
Thanks a lot! Seems much better. 

Result after running "node-waf configure build test": 

```
$ node-waf configure build test
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/vs/.node_libraries 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.372s)
Waf: Entering directory `/Users/vs/Sites/libspotify-node/build'
[ 1/11] cxx: src/search.cc -> build/default/src/search_1.o
[ 5/11] cxx: src/track.cc -> build/default/src/track_1.o
[ 6/11] cxx: src/index.cc -> build/default/src/index_1.o
[ 7/11] cxx: src/playlistcontainer.cc -> build/default/src/playlistcontainer_1.o
[ 8/11] cxx: src/session.cc -> build/default/src/session_1.o
[ 9/11] cxx: src/playlist.cc -> build/default/src/playlist_1.o
[10/11] cxx: src/callback_queue.cc -> build/default/src/callback_queue_1.o
[11/11] cxx_link: build/default/src/search_1.o build/default/src/album_1.o build/default/src/artist_1.o build/default/src/user_1.o build/default/src/track_1.o build/default/src/index_1.o build/default/src/playlistcontainer_1.o build/default/src/session_1.o build/default/src/playlist_1.o build/default/src/callback_queue_1.o -> build/default/binding.node
Waf: Leaving directory `/Users/vs/Sites/libspotify-node/build'
'build' finished successfully (4.446s)
>>> running 8 tests
>>> run test-login.js
>>> fail test-login.js -- status null
>>> ran 1 of 8 tests with 1 failure(s)
tests failed
```

Although if I run "sudo node-waf install" it runs fine and also when running "node test/all.js" a lot of things happen. Seems like it works fine. Will test more another day, now back to the friday party. Again, thanks for your time. =)

**Comment by liesen** [comment]
There are still bugs left to squash, please help out if you can :-)

**Comment by MPV** [comment]
Sure, I'll do my best. 

I have found two bugs so far, the path used in the require() in the files examples/create-playlists.js and dump-playlists.js are wrong. 

Now:
    spotify = require('./spotify'),
    account = require('./account');

Should be:
    spotify = require('../spotify'),
    account = require('../account');

I will look for more and maybe the next time I will submit a patch instead.
