### ISSUE TITLE
build with libspotify 0.6 on unbuntu?

### ISSUE THREAD

**Issue by adriengibrat** [liesen/libspotify-node#3]
Hello,

First thanks for this great project ;) I'm not a C developer, i've done what i could to make it work, but i'm stuck.

I've installed libspotify 0.6, nodejs 0.2.6 and latest libspotify-node commit https://github.com/liesen/libspotify-node/commit/9d5ec12c3a33cd71936c3161737007324c637984
I had to make some very small changes in your source code in order to build...

here is what i've done : http://pastebin.com/NAVKu3NV

here is the patch : http://pastebin.com/hRpF9yDh

And finally the error from libspotify on first test:

running 8 tests
run test-login.js
node.js:63
    throw e;
Error: libspotify.so.6: cannot open shared object file: No such file or directory
    at Module._loadObjectSync (node.js:360:13)
    at Module.loadSync (node.js:336:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/ubuntu/libspotify-node/spotify/index.js:1:77)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
fail test-login.js -- status 1
ran 1 of 8 tests with 1 failure(s)

Any help / advices is welcome!

**Comment by adriengibrat** [comment]
Thanks ;) I'm trying your new commit right now!

**Comment by liesen** [comment]
I manually applied the changes you provided. Still some bugs to squash. Please test, and if you feel like hacking: do so and send a pull request.
